version: '3.2'
services:
  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_SHARED_BUFFERS: 8GB
      POSTGRES_WORK_MEM: 256MB
      POSTGRES_MAINTENANCE_WORK_MEM: 2GB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 15GB
    command: postgres -c max_connections=300 -c shared_buffers=6GB -c effective_cache_size=12GB -c maintenance_work_mem=2GB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB -c default_statistics_target=500 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=8388kB -c min_wal_size=1GB -c max_wal_size=2GB
    ports:
      - "5432:5432"
  db-init:
    image: postgres:15
    entrypoint: ["/bin/sh", "-c", "createdb -h db -U postgres snomio"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
    driver: local